name: Deploy to Vercel

description: 'Deploys Services to Vercel.'


runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-vercel-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-vercel

    - name: Install dependencies
      run: npm install
      shell: bash 

    - name: Build project
      run: npm run build
      shell: bash 

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      run: npx vercel --prod --token $VERCEL_TOKEN
      shell: bash 
