name: Release

on:
  workflow_call:  
  push:
    branches:
      - main  

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - app-name: frontend
          - app-name: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests for ${{ matrix.instance.app-name }}
        uses: ./.github/actions/unit-tests
        with:
          app-name: ${{ matrix.instance.app-name }}

      - name: Build and push Docker image for ${{ matrix.instance.app-name }}
        uses: ./.github/actions/docker-image
        with:
          app-name: ${{ matrix.instance.app-name }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
