name: Release

on:
  workflow_call:  
  push:
    branches:
      - main  

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - { name: frontend, app-name: frontend }
          - { name: backend, app-name: backend }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests for ${{ matrix.instance.app-name }}
        uses: ./.github/actions/unit-tests/action.yml
        with:
          app-name: ${{ matrix.instance.app-name }}
